"""Fix_user_analitics

Revision ID: 0df47de0c5f1
Revises: 780a71f74536
Create Date: 2023-02-15 20:34:17.001513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df47de0c5f1'
down_revision = '780a71f74536'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
