"""2023_07_23_add_advert_strategy

Revision ID: 1660ede742a0
Revises: 8ef16764d33d
Create Date: 2023-07-23 11:48:52.465677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1660ede742a0'
down_revision = '8ef16764d33d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adverts', sa.Column('strategy', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adverts', 'strategy')
    # ### end Alembic commands ###
