"""changes  in action_history model

Revision ID: 1b32bfd6f251
Revises: 0e4b893efc4b
Create Date: 2023-03-11 18:55:46.628895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b32bfd6f251'
down_revision = '0e4b893efc4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_history', sa.Column('action_description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_history', 'action_description')
    # ### end Alembic commands ###
