"""changes_Subscription_v2

Revision ID: 1b96b1b7ded8
Revises: 9ef9e96a21c7
Create Date: 2023-02-01 11:59:42.134764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b96b1b7ded8'
down_revision = '9ef9e96a21c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('subscriptions', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('subscriptions', 'description')
    # ### end Alembic commands ###
