"""Test migrations to_create user_analitics

Revision ID: 21455f5c9dee
Revises: dc7e6b5b853d
Create Date: 2023-05-04 17:00:22.652484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21455f5c9dee'
down_revision = 'dc7e6b5b853d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_budget_analitics_logs', 'adverts', ['campaign_id'], ['id'])
    op.create_foreign_key(None, 'user_budget_analitics_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_budget_analitics_logs', type_='foreignkey')
    op.drop_constraint(None, 'user_budget_analitics_logs', type_='foreignkey')
    # ### end Alembic commands ###
