"""17-06-2023-16:30-add tracking_advertising

Revision ID: 260c8cfb2252
Revises: b37b8e7fb350
Create Date: 2023-06-17 15:28:07.189040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260c8cfb2252'
down_revision = 'b37b8e7fb350'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('tracking_advertising', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'tracking_advertising')
    # ### end Alembic commands ###
