"""Fix_user_analitics4

Revision ID: 2889f488129d
Revises: 4b196726fc7f
Create Date: 2023-02-15 20:48:21.942108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2889f488129d'
down_revision = '4b196726fc7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
