"""access_level

Revision ID: 410295effee3
Revises: 1660ede742a0
Create Date: 2023-08-16 15:20:21.644244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410295effee3'
down_revision = '1660ede742a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wbscraper_product_position')
    op.add_column('subscriptions', sa.Column('access_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'access_level')
    op.create_table('wbscraper_product_position',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_product', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('serarch_word', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('date_collected', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='wbscraper_product_position_pkey')
    )
    # ### end Alembic commands ###
