"""Fix_user_analitics2

Revision ID: 49bce9d45bfe
Revises: 0df47de0c5f1
Create Date: 2023-02-15 20:39:58.838692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49bce9d45bfe'
down_revision = '0df47de0c5f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
