"""Fix_user_analitics3

Revision ID: 4b196726fc7f
Revises: 49bce9d45bfe
Create Date: 2023-02-15 20:41:52.990802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b196726fc7f'
down_revision = '49bce9d45bfe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
