"""2023_05_17_12_16_update GTP_Transaction and Subscription

Revision ID: 4d641ac1086b
Revises: 7dec6e7cc87a
Create Date: 2023-05-17 12:16:04.407515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d641ac1086b'
down_revision = '7dec6e7cc87a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gpt_transactions', sa.Column('token_amount', sa.Integer(), nullable=True))
    op.add_column('gpt_transactions', sa.Column('request_amount', sa.Integer(), nullable=True))
    op.drop_column('gpt_transactions', 'amount')
    op.add_column('subscriptions', sa.Column('requests_get', sa.Integer(), nullable=True))
    op.drop_column('subscriptions', 'tokens_get')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('tokens_get', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('subscriptions', 'requests_get')
    op.add_column('gpt_transactions', sa.Column('amount', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('gpt_transactions', 'request_amount')
    op.drop_column('gpt_transactions', 'token_amount')
    # ### end Alembic commands ###
