"""Create table Stat_word

Revision ID: 644577748eb4
Revises: 724341438949
Create Date: 2023-04-04 22:18:00.280797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644577748eb4'
down_revision = '724341438949'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_words', sa.Column('status', sa.String(), nullable=False))
    op.add_column('stat_words', sa.Column('word_type', sa.String(), nullable=False))
    op.create_foreign_key(None, 'stat_words', 'adverts', ['campaing_id'], ['id'])
    op.drop_column('stat_words', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_words', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stat_words', type_='foreignkey')
    op.drop_column('stat_words', 'word_type')
    op.drop_column('stat_words', 'status')
    # ### end Alembic commands ###
