"""add x_supplier_id

Revision ID: 6ec637a9c9a1
Revises: c09588b96162
Create Date: 2023-05-11 21:56:40.445376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec637a9c9a1'
down_revision = 'c09588b96162'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
