"""Create table Stat_word

Revision ID: 7028158fda4b
Revises: 644577748eb4
Create Date: 2023-04-04 22:22:54.995630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7028158fda4b'
down_revision = '644577748eb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stat_words_campaing_id_fkey', 'stat_words', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('stat_words_campaing_id_fkey', 'stat_words', 'adverts', ['campaing_id'], ['id'])
    # ### end Alembic commands ###
