"""changes in action_history model /change description

Revision ID: 724341438949
Revises: 1b32bfd6f251
Create Date: 2023-03-11 19:16:17.176482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724341438949'
down_revision = '1b32bfd6f251'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_history')
    # ### end Alembic commands ###
