"""adverts

Revision ID: 74409b6acba3
Revises: 370e10261897
Create Date: 2023-01-20 22:13:25.579821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74409b6acba3'
down_revision = '370e10261897'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
