"""2023_16_05_22_38_add_column_into_user_analitics

Revision ID: 7dec6e7cc87a
Revises: 4f92abe37977
Create Date: 2023-05-16 22:44:39.551867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dec6e7cc87a'
down_revision = '4f92abe37977'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_analitics', sa.Column('campaign_id', sa.Integer(), nullable=False))
    op.add_column('user_analitics', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_analitics', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_analitics', type_='foreignkey')
    op.drop_column('user_analitics', 'user_id')
    op.drop_column('user_analitics', 'campaign_id')
    # ### end Alembic commands ###
