"""Test migrations to_create user_analitics2

Revision ID: 7ee9b35b0327
Revises: 21455f5c9dee
Create Date: 2023-05-04 17:09:19.096959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee9b35b0327'
down_revision = '21455f5c9dee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_analitics')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_analitics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('max_bid_company', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_budget_company', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_bet', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('economy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_analitics_pkey')
    )
    pass
    # ### end Alembic commands ###
