"""Create user_logs/action_history

Revision ID: 8422c3e7d8a9
Revises: b53797b51f01
Create Date: 2023-03-02 21:14:59.576692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8422c3e7d8a9'
down_revision = 'b53797b51f01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
