"""add public api token

Revision ID: 8ef16764d33d
Revises: 66d42923510b
Create Date: 2023-07-15 14:15:59.941890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef16764d33d'
down_revision = '66d42923510b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('action_history', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('users', sa.Column('public_api_token', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'public_api_token')
    op.alter_column('action_history', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
