"""Add_relationship_to_user

Revision ID: 9ea0eb01e966
Revises: 43dd04e2cf07
Create Date: 2023-01-20 18:12:52.553399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea0eb01e966'
down_revision = '43dd04e2cf07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
