"""changes_Subscription

Revision ID: 9ef9e96a21c7
Revises: b4df955a330c
Create Date: 2023-02-01 11:55:25.603328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef9e96a21c7'
down_revision = 'b4df955a330c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscriptions_user_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'user_id')
    op.add_column('users', sa.Column('subscriptions_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'subscriptions', ['subscriptions_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'subscriptions_id')
    op.add_column('subscriptions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('subscriptions_user_id_fkey', 'subscriptions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
