"""some fixes with model 'Action_history'

Revision ID: a041a034d4d9
Revises: 8422c3e7d8a9
Create Date: 2023-03-02 21:20:16.353254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a041a034d4d9'
down_revision = '8422c3e7d8a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
