"""update user table add email and password

Revision ID: b37b8e7fb350
Revises: f45925338092
Create Date: 2023-05-22 19:55:31.581684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37b8e7fb350'
down_revision = 'f45925338092'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_analitics', sa.Column('campaign_id', sa.Integer(), nullable=False))
    op.add_column('user_analitics', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_analitics', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.alter_column('users', 'telegram_user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('users', 'telegram_chat_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_chat_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('users', 'telegram_user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'user_analitics', type_='foreignkey')
    op.drop_column('user_analitics', 'user_id')
    op.drop_column('user_analitics', 'campaign_id')
    # ### end Alembic commands ###
