"""Fix_user_analitics5

Revision ID: b53797b51f01
Revises: 2889f488129d
Create Date: 2023-02-15 20:59:05.263962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53797b51f01'
down_revision = '2889f488129d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
