"""2023-05-06-18-fix Advert

Revision ID: c09588b96162
Revises: c513b0e181f5
Create Date: 2023-05-06 18:40:52.689453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c09588b96162'
down_revision = 'c513b0e181f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adverts', sa.Column('max_bid', sa.Integer(), nullable=False))
    op.drop_column('adverts', 'max_budget')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adverts', sa.Column('max_budget', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('adverts', 'max_bid')
    # ### end Alembic commands ###
