"""Test migrations to_create user_analitics3

Revision ID: c513b0e181f5
Revises: 7ee9b35b0327
Create Date: 2023-05-04 17:10:15.954011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c513b0e181f5'
down_revision = '7ee9b35b0327'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_analitics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_bid_company', sa.Integer(), nullable=False),
    sa.Column('max_budget_company', sa.Integer(), nullable=False),
    sa.Column('current_bet', sa.Integer(), nullable=False),
    sa.Column('economy', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_analitics')
    # ### end Alembic commands ###
