"""rename wb_main_token to wb_v3_main_token-2023-05-13-00:06

Revision ID: d79c2cc13e4e
Revises: 4c07efe2478a
Create Date: 2023-05-12 23:06:34.484459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79c2cc13e4e'
down_revision = '4c07efe2478a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wb_v3_main_token', sa.String(length=2048), nullable=True))
    op.drop_column('users', 'wb_main_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wb_main_token', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.drop_column('users', 'wb_v3_main_token')
    # ### end Alembic commands ###
