"""empty message

Revision ID: db8ae22db4c9
Revises: 377cded03882
Create Date: 2023-01-22 21:06:31.343184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8ae22db4c9'
down_revision = '377cded03882'
branch_labels = None
depends_on = None


def upgrade() -> None:

    op.alter_column('users', 'time_updated', server_default=sa.text('now()'))
    op.alter_column('adverts', 'time_updated', server_default=sa.text('now()'))

    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
