"""Test migrations for user_analitics

Revision ID: dc7e6b5b853d
Revises: 18a249916f50
Create Date: 2023-05-04 16:45:23.032800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc7e6b5b853d'
down_revision = '18a249916f50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adverts', 'max_budget', nullable=False, new_column_name='max_bid')
    op.add_column('user_analitics', sa.Column('max_bid_company', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_analitics', 'max_bid_company')
    op.alter_column('adverts', 'max_bid', nullable=False, new_column_name='max_budget')
    # ### end Alembic commands ###
