"""2023_05_17_15_40_fix transaction table and update gpt_transaction table

Revision ID: f45925338092
Revises: 4d641ac1086b
Create Date: 2023-05-17 14:39:46.036496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45925338092'
down_revision = '4d641ac1086b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gpt_transactions', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('transactions', 'subscription_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'subscription_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('gpt_transactions', 'time_created')
    # ### end Alembic commands ###
