"""Add_relationship_to_user

Revision ID: 370e10261897
Revises: 9ea0eb01e966
Create Date: 2023-01-20 18:55:48.822895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370e10261897'
down_revision = '9ea0eb01e966'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('active_adverts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_adverts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('max_budget', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('place', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='active_adverts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='active_adverts_pkey')
    )
    # ### end Alembic commands ###
