"""time_updates_v1

Revision ID: 377cded03882
Revises: 74409b6acba3
Create Date: 2023-01-21 18:07:57.554658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377cded03882'
down_revision = '74409b6acba3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # op.add_column('adverts', sa.Column('compagin_id', sa.Integer(), nullable=False, server_default=0))
    op.add_column('adverts', sa.Column('compagin_id', sa.Integer()))
    op.execute('UPDATE adverts SET compagin_id=0')
    op.alter_column('adverts', 'compagin_id', nullable=False)

    op.add_column('adverts', sa.Column('status', sa.String(), nullable=False, server_default='Dont have status'))
    op.alter_column('adverts', 'status', server_default=None)

    op.add_column('adverts', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('adverts', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'time_updated')
    op.drop_column('users', 'time_created')
    op.drop_column('adverts', 'time_updated')
    op.drop_column('adverts', 'time_created')
    op.drop_column('adverts', 'status')
    op.drop_column('adverts', 'compagin_id')
    # ### end Alembic commands ###
