"""create_transaction

Revision ID: 61021754cfa3
Revises: 1b96b1b7ded8
Create Date: 2023-02-02 14:42:12.117924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61021754cfa3'
down_revision = '1b96b1b7ded8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('total', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('transactions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('subscription_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'subscriptions', ['user_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'subscriptions', ['subscription_id'], ['id'])
    op.drop_column('transactions', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'subscription_id')
    op.drop_column('transactions', 'user_id')
    op.drop_column('transactions', 'time_created')
    op.drop_column('transactions', 'total')
    # ### end Alembic commands ###
