name: base prod redeploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
    
      - name: redeploy prod on test server
        env:
            PRIVATE_KEY:  ${{ secrets.PROD_PRIVATE_KEY  }}
            HOSTNAME :    ${{ secrets.PROD_SSH_HOST  }}
            USER_NAME :   ${{ secrets.PROD_SSH_USER  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && 
          chmod 600 private_key
          
          ssh -v -o StrictHostKeyChecking=off -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /root/data &&
            git fetch --all &&
            git checkout master &&
            git reset --hard origin/master &&
            git pull origin master &&
            bash deploy/deploy.bash
          '
