name: base prod redeploy

on:
  push:
    branches:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest aiohttp pytest-asyncio
          # Добавьте сюда другие зависимости, если они есть

      - name: Run integration tests
        run: pytest src/tests/integration/test_wb_queries.py
    
      - name: redeploy prod on test server
        env:
            PRIVATE_KEY:  ${{ secrets.PROD_PRIVATE_KEY  }}
            HOSTNAME :    ${{ secrets.PROD_SSH_HOST  }}
            USER_NAME :   ${{ secrets.PROD_SSH_USER  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && 
          chmod 600 private_key
          
          ssh -o StrictHostKeyChecking=off -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /data &&
            git fetch --all &&
            git checkout master &&
            git reset --hard origin/master &&
            git pull origin master &&
            bash deploy/deploy.bash
          '
